FROM python:3.11.4-slim-buster as builder

LABEL authors="yulianbohomol"

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y --no-install-recommends gcc

RUN pip install --upgrade pip

COPY ./requirements.txt .

RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt

COPY . .

FROM --platform=linux/aarch64 python:3.11.4-slim-buster

RUN mkdir -p /home/app

RUN addgroup --system app && adduser --system --group app

ENV HOME=/home/app

ENV APP_HOME=/home/app/web

RUN mkdir $APP_HOME

RUN mkdir $APP_HOME/staticfiles

WORKDIR $APP_HOME

RUN apt-get update && apt-get install -y --no-install-recommends netcat ffmpeg libsm6 libxext6

COPY --from=builder /usr/src/app/wheels /wheels

COPY --from=builder /usr/src/app/requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache /wheels/*

COPY ./docker-entrypoint.prod.sh .

RUN sed -i 's/\r$//g' $APP_HOME/docker-entrypoint.prod.sh

RUN chmod +x $APP_HOME/docker-entrypoint.prod.sh

COPY . $APP_HOME

RUN chown -R app:app $APP_HOME

USER app

RUN chmod +x ./docker-entrypoint.prod.sh

ENTRYPOINT ["bash", "./docker-entrypoint.prod.sh"]







