# Generated by Django 4.2.9 on 2024-01-15 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAiModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        default="undefined", max_length=40, verbose_name="Model Name"
                    ),
                ),
                (
                    "desc_name",
                    models.CharField(
                        default="undefined",
                        max_length=80,
                        verbose_name="Description Name",
                    ),
                ),
                ("image", models.ImageField(upload_to="models_images")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
