# Generated by Django 4.2.9 on 2024-01-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_url",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
