# Generated by Django 4.2.9 on 2024-01-09 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0004_alter_usernotifications_notifications"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserNotifications",
            new_name="UserNotification",
        ),
    ]
