# Generated by Django 4.2.9 on 2024-01-09 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_rename_usernotifications_usernotification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usernotification",
            old_name="notifications",
            new_name="user",
        ),
    ]
