# Generated by Django 4.2.9 on 2024-01-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AiModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        default="undefined", max_length=40, verbose_name="Model Name"
                    ),
                ),
                (
                    "desc_name",
                    models.CharField(
                        default="undefined",
                        max_length=80,
                        verbose_name="Description Name",
                    ),
                ),
                ("image", models.ImageField(upload_to="models_images")),
            ],
        ),
    ]
