# Generated by Django 4.2.9 on 2024-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="description",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
