# Generated by Django 4.2.9 on 2024-03-02 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_model", "0002_aimodel_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodel",
            options={"permissions": [("can_view", "Can view")]},
        ),
    ]
