# Generated by Django 4.2.9 on 2024-03-02 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_model", "0003_alter_aimodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aimodel",
            options={},
        ),
    ]
