# Generated by Django 4.2.9 on 2024-10-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builtin_model", "0004_alter_aimodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="image",
            field=models.CharField(max_length=512),
        ),
    ]
