# Generated by Django 4.2.8 on 2023-12-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
